In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string

In [3]:
df = pd.read_csv('all_songs_data_50k.csv')
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
0,6853b58d17e1fe68eff7d1bf,mark,"Hi, uhm, yeah, everytime na tingnan ko yung re...",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-19T07:00:29.319655884Z
1,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z
2,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z
3,6853b56717e1fe68eff7d1bc,savira ramadhani m,.,6GCW5Muk3u0cM5QTkS4C9a,The One That Got Away,Katy Perry,https://i.scdn.co/image/ab67616d0000b27343219f...,2025-06-19T06:59:51.325948562Z
4,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z
...,...,...,...,...,...,...,...,...
49995,684ee56f17e1fe68eff710d6,joshua,"hii exx, bahagiaa terus yaa\nmaaf kaloo sering...",4E8rZD1xKIbof0vUkyHJLn,"Here, There And Everywhere - 2022 Mix",The Beatles,https://i.scdn.co/image/ab67616d0000b2734a4c74...,2025-06-15T15:23:27.353310546Z
49996,684ee56c17e1fe68eff710d5,yna,bab,0D1ecMMsSIpJbjPoJMHGkV,Your Song,Parokya Ni Edgar,https://i.scdn.co/image/ab67616d0000b273cf7889...,2025-06-15T15:23:24.209151483Z
49997,684ee56b17e1fe68eff710d4,maritza,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,15LSJbO8lAck7j25HBA581,i've always loved you,Arash Buana,https://i.scdn.co/image/ab67616d0000b273687cac...,2025-06-15T15:23:23.834725361Z
49998,684ee56b17e1fe68eff710d3,alfred,Hindi ko naman yata ikamamatay\nKung crush par...,29eiVZ3R6iJcXB01dOAl6H,Waltz of Four Left Feet,Shirebound & Busking,https://i.scdn.co/image/ab67616d0000b27342f6ca...,2025-06-15T15:23:23.693217217Z
49999,684ee56217e1fe68eff710d2,awik,aku naksir parah sama kamuu..,21acb66djKRlDPJOXRBCkc,Take A Chance With Me,NIKI,https://i.scdn.co/image/ab67616d0000b273d3997a...,2025-06-15T15:23:14.026978056Z

# DATA PREPROCESSING

In [7]:
message = df['message']
message

0        Hi, uhm, yeah, everytime na tingnan ko yung re...
1        I don't know if you still care about me or not...
2        I'll always love you from this day on, now and...
3                                                        .
4        hi drix, i hope when out paths met again, sana...
                               ...
49995    hii exx, bahagiaa terus yaa\nmaaf kaloo sering...
49996                                                  bab
49997    HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...
49998    Hindi ko naman yata ikamamatay\nKung crush par...
49999                        aku naksir parah sama kamuu..
Name: message, Length: 50000, dtype: object

In [8]:
# convert message to lowercase
message = message.str.lower()
message

0        hi, uhm, yeah, everytime na tingnan ko yung re...
1        i don't know if you still care about me or not...
2        i'll always love you from this day on, now and...
3                                                        .
4        hi drix, i hope when out paths met again, sana...
                               ...
49995    hii exx, bahagiaa terus yaa\nmaaf kaloo sering...
49996                                                  bab
49997    happy birthday!!!🤍 untukk adlina maritza yangg...
49998    hindi ko naman yata ikamamatay\nkung crush par...
49999                        aku naksir parah sama kamuu..
Name: message, Length: 50000, dtype: object

In [10]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [12]:
# Remove punctuation(tanda baca) function
def remove_punctuation(text):
   return text.translate(str.maketrans('', '', string.punctuation))

In [ ]:
message = message.apply(lambda x: remove_punctuation(x))
message

In [5]:
df[df.duplicated()]

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
15,6853b52917e1fe68eff7d1b1,fitri,nyebelin lo egois njs,1GCbc1vpkZA2zhjsSFhmHT,Fuck You,Lily Allen,https://i.scdn.co/image/ab67616d0000b2737124b6...,2025-06-19T06:58:49.9888968Z
105,6853b27b17e1fe68eff7d158,teagan,"Hey T, I know that you don’t know what you did...",5W6BA8Wa8JZGKdliH2gkwO,She Likes Another Boy,Oscar Lang,https://i.scdn.co/image/ab67616d0000b2737b3ad9...,2025-06-19T06:47:23.746468173Z
345,6853ab2117e1fe68eff7d06a,yekai,(🙇🏻‍♀️?) niyayakap niya knees niya tapos nakay...,0IktbUcnAGrvD03AWnz3Q8,Lucky,"Jason Mraz, Colbie Caillat",https://i.scdn.co/image/ab67616d0000b273125b1a...,2025-06-19T06:16:01.525060951Z
346,6853ab1517e1fe68eff7d069,faathir k,"hllo thir! kalo lu tau ttg ini one day, all i ...",1Ib0UNLoqBEWTmBvXeFSni,Pemuja Rahasia,Sheila On 7,https://i.scdn.co/image/ab67616d0000b273f0a7ef...,2025-06-19T06:15:49.843392627Z
495,6853a64617e1fe68eff7cfd5,chang,maybe in another universe ill be able to conve...,68FHdrL6dbruEBrfLjR52a,Paths,NIKI,https://i.scdn.co/image/ab67616d0000b2734d3d39...,2025-06-19T05:55:18.009760701Z
...,...,...,...,...,...,...,...,...
49530,684eeb3017e1fe68eff712a3,bea,"hey, bei! Kumusta ka? I hope u’re doing good! ...",3r9eGg4SVPbhtiPTA9UkmK,us,keshi,https://i.scdn.co/image/ab67616d0000b273563944...,2025-06-15T15:48:00.376251019Z
49575,684eea9d17e1fe68eff71277,ara,"iya kaya gini loh, ah lu gimana sih paham ga?",5tyGpIXFvaSwfCx2A82rR8,Goyang Dumang,Cita Citata,https://i.scdn.co/image/ab67616d0000b2735f574c...,2025-06-15T15:45:33.400855956Z
49635,684eea0417e1fe68eff7123c,ramaaaaaa,"hii, lovee uuu",5xCsdnbeg7yhVX2qlRaDUw,I Love You 3000,Stephanie Poetri,https://i.scdn.co/image/ab67616d0000b2737ccc25...,2025-06-15T15:43:00.990060136Z
49935,684ee65217e1fe68eff71111,rama,im so sorry,09CtPGIpYB4BrO8qb1RGsF,Sorry,Justin Bieber,https://i.scdn.co/image/ab67616d0000b273f46b9d...,2025-06-15T15:27:14.020932797Z
49980,684ee5a117e1fe68eff710e5,rohn,"sure, u put urself into this.",6qpT0nzHUn52gnSWYdbxF4,You Broke My Heart Again,"Teqkoi, Aiko",https://i.scdn.co/image/ab67616d0000b2732708d8...,2025-06-15T15:24:17.112581783Z

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _id          50000 non-null  object
 1   recipient    50000 non-null  object
 2   message      49999 non-null  object
 3   song_id      50000 non-null  object
 4   song_name    50000 non-null  object
 5   song_artist  50000 non-null  object
 6   song_image   49999 non-null  object
 7   created_at   50000 non-null  object
dtypes: object(8)
memory usage: 3.1+ MB

## Unique Category

In [ ]:
print('song artist sum    : ', df['song_artist'].unique().shape[0])
print('song name sum      : ', df['song_name'].unique().shape[0])

song artist sum    :  1927
song name sum      :  3934

In [23]:
empty_message = df['message'].isnull().sum() + df['message'].eq('').sum() + df['message'].eq(' ').sum() + df['message'].eq('.').sum() + df['message'].eq(',').sum()
print('empty message sum : ', empty_message)

empty message sum :  402