In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string

# DATA PREPROCESSING

## Data Loading

In [2]:
df = pd.read_csv('datasets/all_songs_data_50k.csv')
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
0,6853b58d17e1fe68eff7d1bf,mark,"Hi, uhm, yeah, everytime na tingnan ko yung re...",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-19T07:00:29.319655884Z
1,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z
2,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z
3,6853b56717e1fe68eff7d1bc,savira ramadhani m,.,6GCW5Muk3u0cM5QTkS4C9a,The One That Got Away,Katy Perry,https://i.scdn.co/image/ab67616d0000b27343219f...,2025-06-19T06:59:51.325948562Z
4,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z
...,...,...,...,...,...,...,...,...
49995,684ee56f17e1fe68eff710d6,joshua,"hii exx, bahagiaa terus yaa\nmaaf kaloo sering...",4E8rZD1xKIbof0vUkyHJLn,"Here, There And Everywhere - 2022 Mix",The Beatles,https://i.scdn.co/image/ab67616d0000b2734a4c74...,2025-06-15T15:23:27.353310546Z
49996,684ee56c17e1fe68eff710d5,yna,bab,0D1ecMMsSIpJbjPoJMHGkV,Your Song,Parokya Ni Edgar,https://i.scdn.co/image/ab67616d0000b273cf7889...,2025-06-15T15:23:24.209151483Z
49997,684ee56b17e1fe68eff710d4,maritza,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,15LSJbO8lAck7j25HBA581,i've always loved you,Arash Buana,https://i.scdn.co/image/ab67616d0000b273687cac...,2025-06-15T15:23:23.834725361Z
49998,684ee56b17e1fe68eff710d3,alfred,Hindi ko naman yata ikamamatay\nKung crush par...,29eiVZ3R6iJcXB01dOAl6H,Waltz of Four Left Feet,Shirebound & Busking,https://i.scdn.co/image/ab67616d0000b27342f6ca...,2025-06-15T15:23:23.693217217Z
49999,684ee56217e1fe68eff710d2,awik,aku naksir parah sama kamuu..,21acb66djKRlDPJOXRBCkc,Take A Chance With Me,NIKI,https://i.scdn.co/image/ab67616d0000b273d3997a...,2025-06-15T15:23:14.026978056Z

## Data Cleaning

### Remove Non-Indonesian/English Words

using langdetect

In [4]:
from langdetect import detect, LangDetectException

def is_indonesian_or_english(text):
    # Only process non-empty strings
    if not isinstance(text, str) or not text.strip():
        return False
    try:
        # Detect the language of the text
        lang = detect(text)
        # Return True if the language is Indonesian or English
        return lang in ['id', 'en']
    except LangDetectException:
        # If language detection fails, assume it's not the desired language
        return False

In [5]:
# Apply the function to the 'message' column and keep only the rows that return True
df = df[df['message'].apply(is_indonesian_or_english)]

# Display the first few rows of the filtered DataFrame
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
1,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z
2,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z
4,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z
6,6853b56317e1fe68eff7d1b9,jitsu,y ur so pogi and ur so holyyyy jk,3hUxzQpSfdDqwM3ZTFQY0K,august,Taylor Swift,https://i.scdn.co/image/ab67616d0000b27395f754...,2025-06-19T06:59:47.468141291Z
8,6853b55217e1fe68eff7d1b7,amann,"hi kak, aku lihat kayaknya kamu beneran deket ...",1ZWLWVqeEMWMKTlteS0yLH,Love You Goodbye,One Direction,https://i.scdn.co/image/ab67616d0000b273241e4f...,2025-06-19T06:59:30.953684475Z
...,...,...,...,...,...,...,...,...
49992,684ee57517e1fe68eff710d9,erin,"yang kangen sama erin, i'm erin. i also miss uu\n",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-15T15:23:33.485942635Z
49993,684ee57417e1fe68eff710d8,fadhly,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,2AKtROlRcuo37UhkDWiuY5,My Love,Westlife,https://i.scdn.co/image/ab67616d0000b273ee8ea4...,2025-06-15T15:23:32.358975576Z
49994,684ee57317e1fe68eff710d7,jordy,u said you didnt want a relationship right aft...,0KqlLyIGuBZWqzNwP9rypc,Last First Kiss,One Direction,https://i.scdn.co/image/ab67616d0000b2734e31e0...,2025-06-15T15:23:31.048231744Z
49997,684ee56b17e1fe68eff710d4,maritza,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,15LSJbO8lAck7j25HBA581,i've always loved you,Arash Buana,https://i.scdn.co/image/ab67616d0000b273687cac...,2025-06-15T15:23:23.834725361Z
49999,684ee56217e1fe68eff710d2,awik,aku naksir parah sama kamuu..,21acb66djKRlDPJOXRBCkc,Take A Chance With Me,NIKI,https://i.scdn.co/image/ab67616d0000b273d3997a...,2025-06-15T15:23:14.026978056Z

In [7]:
df.to_csv('indo-english-messageDataset.csv', index=False, encoding='utf-8')

In [3]:
df = pd.read_csv('datasets/indo-english-messageDataset.csv')

### Delete Duplicate Data

In [4]:
# search for duplicates
duplicates = df[df.duplicated(subset=['_id'], keep=False)]
duplicates

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
65,6853b27b17e1fe68eff7d158,teagan,"Hey T, I know that you don’t know what you did...",5W6BA8Wa8JZGKdliH2gkwO,She Likes Another Boy,Oscar Lang,https://i.scdn.co/image/ab67616d0000b2737b3ad9...,2025-06-19T06:47:23.746468173Z
66,6853b27b17e1fe68eff7d158,teagan,"Hey T, I know that you don’t know what you did...",5W6BA8Wa8JZGKdliH2gkwO,She Likes Another Boy,Oscar Lang,https://i.scdn.co/image/ab67616d0000b2737b3ad9...,2025-06-19T06:47:23.746468173Z
229,6853ab1517e1fe68eff7d069,faathir k,"hllo thir! kalo lu tau ttg ini one day, all i ...",1Ib0UNLoqBEWTmBvXeFSni,Pemuja Rahasia,Sheila On 7,https://i.scdn.co/image/ab67616d0000b273f0a7ef...,2025-06-19T06:15:49.843392627Z
230,6853ab1517e1fe68eff7d069,faathir k,"hllo thir! kalo lu tau ttg ini one day, all i ...",1Ib0UNLoqBEWTmBvXeFSni,Pemuja Rahasia,Sheila On 7,https://i.scdn.co/image/ab67616d0000b273f0a7ef...,2025-06-19T06:15:49.843392627Z
338,6853a64617e1fe68eff7cfd5,chang,maybe in another universe ill be able to conve...,68FHdrL6dbruEBrfLjR52a,Paths,NIKI,https://i.scdn.co/image/ab67616d0000b2734d3d39...,2025-06-19T05:55:18.009760701Z
...,...,...,...,...,...,...,...,...
32696,684eeb3017e1fe68eff712a3,bea,"hey, bei! Kumusta ka? I hope u’re doing good! ...",3r9eGg4SVPbhtiPTA9UkmK,us,keshi,https://i.scdn.co/image/ab67616d0000b273563944...,2025-06-15T15:48:00.376251019Z
32967,684ee65217e1fe68eff71111,rama,im so sorry,09CtPGIpYB4BrO8qb1RGsF,Sorry,Justin Bieber,https://i.scdn.co/image/ab67616d0000b273f46b9d...,2025-06-15T15:27:14.020932797Z
32968,684ee65217e1fe68eff71111,rama,im so sorry,09CtPGIpYB4BrO8qb1RGsF,Sorry,Justin Bieber,https://i.scdn.co/image/ab67616d0000b273f46b9d...,2025-06-15T15:27:14.020932797Z
32999,684ee5a117e1fe68eff710e5,rohn,"sure, u put urself into this.",6qpT0nzHUn52gnSWYdbxF4,You Broke My Heart Again,"Teqkoi, Aiko",https://i.scdn.co/image/ab67616d0000b2732708d8...,2025-06-15T15:24:17.112581783Z
33000,684ee5a117e1fe68eff710e5,rohn,"sure, u put urself into this.",6qpT0nzHUn52gnSWYdbxF4,You Broke My Heart Again,"Teqkoi, Aiko",https://i.scdn.co/image/ab67616d0000b2732708d8...,2025-06-15T15:24:17.112581783Z

In [5]:
# delete data with the same _id
df = df.drop_duplicates(subset='_id', keep='first')

# check for duplicates again
duplicates = df[df.duplicated(subset=['_id'], keep=False)]
duplicates

Empty DataFrame
Columns: [_id, recipient, message, song_id, song_name, song_artist, song_image, created_at]
Index: []

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32627 entries, 0 to 33012
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _id          32627 non-null  object
 1   recipient    32627 non-null  object
 2   message      32627 non-null  object
 3   song_id      32627 non-null  object
 4   song_name    32627 non-null  object
 5   song_artist  32627 non-null  object
 6   song_image   32626 non-null  object
 7   created_at   32627 non-null  object
dtypes: object(8)
memory usage: 2.2+ MB

### Convert Message to Lowercase

In [7]:
df['clean_message'] = df['message'].str.lower()
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at,clean_message
0,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z,i don't know if you still care about me or not...
1,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z,"i'll always love you from this day on, now and..."
2,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z,"hi drix, i hope when out paths met again, sana..."
3,6853b56317e1fe68eff7d1b9,jitsu,y ur so pogi and ur so holyyyy jk,3hUxzQpSfdDqwM3ZTFQY0K,august,Taylor Swift,https://i.scdn.co/image/ab67616d0000b27395f754...,2025-06-19T06:59:47.468141291Z,y ur so pogi and ur so holyyyy jk
4,6853b55217e1fe68eff7d1b7,amann,"hi kak, aku lihat kayaknya kamu beneran deket ...",1ZWLWVqeEMWMKTlteS0yLH,Love You Goodbye,One Direction,https://i.scdn.co/image/ab67616d0000b273241e4f...,2025-06-19T06:59:30.953684475Z,"hi kak, aku lihat kayaknya kamu beneran deket ..."
...,...,...,...,...,...,...,...,...,...
33008,684ee57517e1fe68eff710d9,erin,"yang kangen sama erin, i'm erin. i also miss uu\n",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-15T15:23:33.485942635Z,"yang kangen sama erin, i'm erin. i also miss uu\n"
33009,684ee57417e1fe68eff710d8,fadhly,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,2AKtROlRcuo37UhkDWiuY5,My Love,Westlife,https://i.scdn.co/image/ab67616d0000b273ee8ea4...,2025-06-15T15:23:32.358975576Z,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...
33010,684ee57317e1fe68eff710d7,jordy,u said you didnt want a relationship right aft...,0KqlLyIGuBZWqzNwP9rypc,Last First Kiss,One Direction,https://i.scdn.co/image/ab67616d0000b2734e31e0...,2025-06-15T15:23:31.048231744Z,u said you didnt want a relationship right aft...
33011,684ee56b17e1fe68eff710d4,maritza,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,15LSJbO8lAck7j25HBA581,i've always loved you,Arash Buana,https://i.scdn.co/image/ab67616d0000b273687cac...,2025-06-15T15:23:23.834725361Z,happy birthday!!!🤍 untukk adlina maritza yangg...
33012,684ee56217e1fe68eff710d2,awik,aku naksir parah sama kamuu..,21acb66djKRlDPJOXRBCkc,Take A Chance With Me,NIKI,https://i.scdn.co/image/ab67616d0000b273d3997a...,2025-06-15T15:23:14.026978056Z,aku naksir parah sama kamuu..

### Remove Punctuations

In [8]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [9]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_punctuation(x) if isinstance(x, str) else x)
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,i dont know if you still care about me or not ...
1,"I'll always love you from this day on, now and...",ill always love you from this day on now and f...
2,"hi drix, i hope when out paths met again, sana...",hi drix i hope when out paths met again sana t...
3,y ur so pogi and ur so holyyyy jk,y ur so pogi and ur so holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak aku lihat kayaknya kamu beneran deket s...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",yang kangen sama erin im erin i also miss uu\n
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...
33010,u said you didnt want a relationship right aft...,u said you didnt want a relationship right aft...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday🤍 untukk adlina maritza yangg ca...
33012,aku naksir parah sama kamuu..,aku naksir parah sama kamuu

### Removal of Stopwords

using NLTK or natural language toolkit

In [10]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

print("Indoensian: ", " ".join(stopwords.words('indonesian')))
print("english   : ", " ".join(stopwords.words('english')))

Indoensian:  ada adalah adanya adapun agak agaknya agar akan akankah akhir akhiri akhirnya aku akulah amat amatlah anda andalah antar antara antaranya apa apaan apabila apakah apalagi apatah artinya asal asalkan atas atau ataukah ataupun awal awalnya bagai bagaikan bagaimana bagaimanakah bagaimanapun bagi bagian bahkan bahwa bahwasanya baik bakal bakalan balik banyak bapak baru bawah beberapa begini beginian beginikah beginilah begitu begitukah begitulah begitupun bekerja belakang belakangan belum belumlah benar benarkah benarlah berada berakhir berakhirlah berakhirnya berapa berapakah berapalah berapapun berarti berawal berbagai berdatangan beri berikan berikut berikutnya berjumlah berkali-kali berkata berkehendak berkeinginan berkenaan berlainan berlalu berlangsung berlebihan bermacam bermacam-macam bermaksud bermula bersama bersama-sama bersiap bersiap-siap bertanya bertanya-tanya berturut berturut-turut bertutur berujar berupa besar betul betulkah biasa biasanya bila bilakah bisa bisakah boleh bolehkah bolehlah buat bukan bukankah bukanlah bukannya bulan bung cara caranya cukup cukupkah cukuplah cuma dahulu dalam dan dapat dari daripada datang dekat demi demikian demikianlah dengan depan di dia diakhiri diakhirinya dialah diantara diantaranya diberi diberikan diberikannya dibuat dibuatnya didapat didatangkan digunakan diibaratkan diibaratkannya diingat diingatkan diinginkan dijawab dijelaskan dijelaskannya dikarenakan dikatakan dikatakannya dikerjakan diketahui diketahuinya dikira dilakukan dilalui dilihat dimaksud dimaksudkan dimaksudkannya dimaksudnya diminta dimintai dimisalkan dimulai dimulailah dimulainya dimungkinkan dini dipastikan diperbuat diperbuatnya dipergunakan diperkirakan diperlihatkan diperlukan diperlukannya dipersoalkan dipertanyakan dipunyai diri dirinya disampaikan disebut disebutkan disebutkannya disini disinilah ditambahkan ditandaskan ditanya ditanyai ditanyakan ditegaskan ditujukan ditunjuk ditunjuki ditunjukkan ditunjukkannya ditunjuknya dituturkan dituturkannya diucapkan diucapkannya diungkapkan dong dua dulu empat enggak enggaknya entah entahlah guna gunakan hal hampir hanya hanyalah hari harus haruslah harusnya hendak hendaklah hendaknya hingga ia ialah ibarat ibaratkan ibaratnya ibu ikut ingat ingat-ingat ingin inginkah inginkan ini inikah inilah itu itukah itulah jadi jadilah jadinya jangan jangankan janganlah jauh jawab jawaban jawabnya jelas jelaskan jelaslah jelasnya jika jikalau juga jumlah jumlahnya justru kala kalau kalaulah kalaupun kalian kami kamilah kamu kamulah kan kapan kapankah kapanpun karena karenanya kasus kata katakan katakanlah katanya ke keadaan kebetulan kecil kedua keduanya keinginan kelamaan kelihatan kelihatannya kelima keluar kembali kemudian kemungkinan kemungkinannya kenapa kepada kepadanya kesampaian keseluruhan keseluruhannya keterlaluan ketika khususnya kini kinilah kira kira-kira kiranya kita kitalah kok kurang lagi lagian lah lain lainnya lalu lama lamanya lanjut lanjutnya lebih lewat lima luar macam maka makanya makin malah malahan mampu mampukah mana manakala manalagi masa masalah masalahnya masih masihkah masing masing-masing mau maupun melainkan melakukan melalui melihat melihatnya memang memastikan memberi memberikan membuat memerlukan memihak meminta memintakan memisalkan memperbuat mempergunakan memperkirakan memperlihatkan mempersiapkan mempersoalkan mempertanyakan mempunyai memulai memungkinkan menaiki menambahkan menandaskan menanti menanti-nanti menantikan menanya menanyai menanyakan mendapat mendapatkan mendatang mendatangi mendatangkan menegaskan mengakhiri mengapa mengatakan mengatakannya mengenai mengerjakan mengetahui menggunakan menghendaki mengibaratkan mengibaratkannya mengingat mengingatkan menginginkan mengira mengucapkan mengucapkannya mengungkapkan menjadi menjawab menjelaskan menuju menunjuk menunjuki menunjukkan menunjuknya menurut menuturkan menyampaikan menyangkut menyatakan menyebutkan menyeluruh menyiapkan merasa mereka merekalah merupakan meski meskipun meyakini meyakinkan minta mirip misal misalkan misalnya mula mulai mulailah mulanya mungkin mungkinkah nah naik namun nanti nantinya nyaris nyatanya oleh olehnya pada padahal padanya pak paling panjang pantas para pasti pastilah penting pentingnya per percuma perlu perlukah perlunya pernah persoalan pertama pertama-tama pertanyaan pertanyakan pihak pihaknya pukul pula pun punya rasa rasanya rata rupanya saat saatnya saja sajalah saling sama sama-sama sambil sampai sampai-sampai sampaikan sana sangat sangatlah satu saya sayalah se sebab sebabnya sebagai sebagaimana sebagainya sebagian sebaik sebaik-baiknya sebaiknya sebaliknya sebanyak sebegini sebegitu sebelum sebelumnya sebenarnya seberapa sebesar sebetulnya sebisanya sebuah sebut sebutlah sebutnya secara secukupnya sedang sedangkan sedemikian sedikit sedikitnya seenaknya segala segalanya segera seharusnya sehingga seingat sejak sejauh sejenak sejumlah sekadar sekadarnya sekali sekali-kali sekalian sekaligus sekalipun sekarang sekarang sekecil seketika sekiranya sekitar sekitarnya sekurang-kurangnya sekurangnya sela selain selaku selalu selama selama-lamanya selamanya selanjutnya seluruh seluruhnya semacam semakin semampu semampunya semasa semasih semata semata-mata semaunya sementara semisal semisalnya sempat semua semuanya semula sendiri sendirian sendirinya seolah seolah-olah seorang sepanjang sepantasnya sepantasnyalah seperlunya seperti sepertinya sepihak sering seringnya serta serupa sesaat sesama sesampai sesegera sesekali seseorang sesuatu sesuatunya sesudah sesudahnya setelah setempat setengah seterusnya setiap setiba setibanya setidak-tidaknya setidaknya setinggi seusai sewaktu siap siapa siapakah siapapun sini sinilah soal soalnya suatu sudah sudahkah sudahlah supaya tadi tadinya tahu tahun tak tambah tambahnya tampak tampaknya tandas tandasnya tanpa tanya tanyakan tanyanya tapi tegas tegasnya telah tempat tengah tentang tentu tentulah tentunya tepat terakhir terasa terbanyak terdahulu terdapat terdiri terhadap terhadapnya teringat teringat-ingat terjadi terjadilah terjadinya terkira terlalu terlebih terlihat termasuk ternyata tersampaikan tersebut tersebutlah tertentu tertuju terus terutama tetap tetapi tiap tiba tiba-tiba tidak tidakkah tidaklah tiga tinggi toh tunjuk turut tutur tuturnya ucap ucapnya ujar ujarnya umum umumnya ungkap ungkapnya untuk usah usai waduh wah wahai waktu waktunya walau walaupun wong yaitu yakin yakni yang
english   :  a about above after again against ain all am an and any are aren aren't as at be because been before being below between both but by can couldn couldn't d did didn didn't do does doesn doesn't doing don don't down during each few for from further had hadn hadn't has hasn hasn't have haven haven't having he he'd he'll her here hers herself he's him himself his how i i'd if i'll i'm in into is isn isn't it it'd it'll it's its itself i've just ll m ma me mightn mightn't more most mustn mustn't my myself needn needn't no nor not now o of off on once only or other our ours ourselves out over own re s same shan shan't she she'd she'll she's should shouldn shouldn't should've so some such t than that that'll the their theirs them themselves then there these they they'd they'll they're they've this those through to too under until up ve very was wasn wasn't we we'd we'll we're were weren weren't we've what when where which while who whom why will with won won't wouldn wouldn't y you you'd you'll your you're yours yourself yourselves you've

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\62812\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [11]:
STOPWORDS = set(stopwords.words('indonesian') + stopwords.words('english'))
def remove_stopwords(text):
   return " ".join([word for word in text.split() if word not in STOPWORDS])

In [12]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_stopwords(x) if isinstance(x, str) else x)
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,dont know still care even distance still care ...
1,"I'll always love you from this day on, now and...",ill always love day forever bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn 🤭 want s...
33010,u said you didnt want a relationship right aft...,u said didnt want relationship right first kis...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday🤍 untukk adlina maritza yangg ca...
33012,aku naksir parah sama kamuu..,naksir parah kamuu

### Removal of Frequent Words

In [13]:
from collections import Counter
word_count = Counter()
for text in df['clean_message']:
    if isinstance(text, str):
        for word in text.split():
             word_count[word] += 1

word_count.most_common(10)

[('u', 13012),
 ('love', 11519),
 ('know', 10040),
 ('im', 9174),
 ('always', 7294),
 ('like', 7285),
 ('ya', 7181),
 ('hope', 7026),
 ('still', 6893),
 ('na', 6318)]

In [14]:
FREQUENT_WORDS = set(word for (word, wc) in word_count.most_common(3))
def remove_frequent_words(text):
    return " ".join([word for word in text.split() if word not in FREQUENT_WORDS])

In [15]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_frequent_words(x) if isinstance(x, str) else x)
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...
1,"I'll always love you from this day on, now and...",ill always day forever bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn 🤭 want s...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday🤍 untukk adlina maritza yangg ca...
33012,aku naksir parah sama kamuu..,naksir parah kamuu

### Remove Emojis

In [17]:
import re

def remove_emojis(text):
    # Return the original value if it's not a string
    if not isinstance(text, str):
        return text
    
    # Comprehensive regex to find most emojis
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U0001FA00-\U0001FA6F"  # Chess Symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U00002702-\U000027B0"  # Dingbats
        "\U000024C2-\U0001F251" 
        "]+",
        flags=re.UNICODE,
    )
    # Remove all emojis from the string
    return emoji_pattern.sub(r'', text)

# Apply the function to the 'stemmed_message' column
df['clean_message'] = df['clean_message'].apply(remove_emojis)

# Display the column to verify the changes
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...
1,"I'll always love you from this day on, now and...",ill always day forever bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn want so...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday untukk adlina maritza yangg can...
33012,aku naksir parah sama kamuu..,naksir parah kamuu

### Remove Rare Words

In [18]:
RARE_WORDS = set(word for (word, wc) in word_count.most_common()[:-10:-1])  # Get the last 10 rarest words
RARE_WORDS

{'ak🫠',
 'always🌷🤍',
 'hehhehe🎂🥰',
 'kau🥹🤍',
 'masalah🙃',
 'tauuu🥹💋💗🫶🏻🤍',
 'tauuu🫂🤍',
 'yee🫰🏻🤍',
 '☺️🤍'}

In [19]:
def remove_rare_words(text):
   return " ".join([word for word in text.split() if word not in RARE_WORDS])

In [20]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_rare_words(x) if isinstance(x, str) else x)
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...
1,"I'll always love you from this day on, now and...",ill always day forever bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn want som...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday untukk adlina maritza yangg can...
33012,aku naksir parah sama kamuu..,naksir parah kamuu

### Remove Special Characters

In [21]:
import re
def remove_spl_chars(text):
   text = re.sub('^a-zA-Z0-9', ' ', text)
   text = re.sub('\s+', ' ', text)
   return text

In [22]:
df['clean_message'] = df['clean_message'].apply(lambda x: remove_spl_chars(x) if isinstance(x, str) else x)
df[['message', 'clean_message']]

,message,clean_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...
1,"I'll always love you from this day on, now and...",ill always day forever bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn want som...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday untukk adlina maritza yangg can...
33012,aku naksir parah sama kamuu..,naksir parah kamuu

## Stemming

In [23]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
def stem_words(text):
   return " ".join([ps.stem(word) for word in text.split()])

In [24]:
df['stemmed_message'] = df['clean_message'].apply(lambda x: stem_words(x) if isinstance(x, str) else x)
df[['message', 'clean_message', 'stemmed_message']]

,message,clean_message,stemmed_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...,dont still care even distanc still care much s...
1,"I'll always love you from this day on, now and...",ill always day forever bee,ill alway day forev bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...,hi drix hope path met tayo na your multo even ...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...,hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu,kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn want som...,ih ih yg ngilang deh kmnya aja yg kgn want som...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday untukk adlina maritza yangg can...,happi birthday untukk adlina maritza yangg can...
33012,aku naksir parah sama kamuu..,naksir parah kamuu,naksir parah kamuu

## Lemmatization & POS Tagging

In [25]:
import nltk
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\62812\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\62812\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [26]:
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {'N': wordnet.NOUN, 'V': wordnet.VERB, 'J': wordnet.ADJ,  'R': wordnet.ADV}

def lemmatize_words(text):
   pos_text = pos_tag(text.split())
   return ' '.join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_text])

In [27]:
df['lemmatized_message'] = df['clean_message'].apply(lambda x: stem_words(x) if isinstance(x, str) else x)
df[['message', 'clean_message', 'stemmed_message', 'lemmatized_message']]

,message,clean_message,stemmed_message,lemmatized_message
0,I don't know if you still care about me or not...,dont still care even distance still care much ...,dont still care even distanc still care much s...,dont still care even distanc still care much s...
1,"I'll always love you from this day on, now and...",ill always day forever bee,ill alway day forev bee,ill alway day forev bee
2,"hi drix, i hope when out paths met again, sana...",hi drix hope paths met tayo na youre multo eve...,hi drix hope path met tayo na your multo even ...,hi drix hope path met tayo na your multo even ...
3,y ur so pogi and ur so holyyyy jk,ur pogi ur holyyyy jk,ur pogi ur holyyyy jk,ur pogi ur holyyyy jk
4,"hi kak, aku lihat kayaknya kamu beneran deket ...",hi kak lihat kayaknya beneran deket wanita yg ...,hi kak lihat kayaknya beneran deket wanita yg ...,hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...,...,...
33008,"yang kangen sama erin, i'm erin. i also miss uu\n",kangen erin im erin also miss uu,kangen erin im erin also miss uu,kangen erin im erin also miss uu
33009,ih ih siapa yg ngilang deh kmnya aja yg kgn ak...,ih ih yg ngilang deh kmnya aja yg kgn want som...,ih ih yg ngilang deh kmnya aja yg kgn want som...,ih ih yg ngilang deh kmnya aja yg kgn want som...
33010,u said you didnt want a relationship right aft...,said didnt want relationship right first kiss ...,said didnt want relationship right first kiss ...,said didnt want relationship right first kiss ...
33011,HAPPY BIRTHDAY!!!🤍 untukk adlina maritza yangg...,happy birthday untukk adlina maritza yangg can...,happi birthday untukk adlina maritza yangg can...,happi birthday untukk adlina maritza yangg can...
33012,aku naksir parah sama kamuu..,naksir parah kamuu,naksir parah kamuu,naksir parah kamuu

## Save Cleaned Dataset

In [28]:
cleaned_df = df.drop(columns=['message', 'lemmatized_message', 'stemmed_message'])
cleaned_df

,_id,recipient,song_id,song_name,song_artist,song_image,created_at,clean_message
0,6853b58717e1fe68eff7d1be,dimas ali,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z,dont still care even distance still care much ...
1,6853b58417e1fe68eff7d1bd,2229,37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z,ill always day forever bee
2,6853b56617e1fe68eff7d1bb,drix,4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z,hi drix hope paths met tayo na youre multo eve...
3,6853b56317e1fe68eff7d1b9,jitsu,3hUxzQpSfdDqwM3ZTFQY0K,august,Taylor Swift,https://i.scdn.co/image/ab67616d0000b27395f754...,2025-06-19T06:59:47.468141291Z,ur pogi ur holyyyy jk
4,6853b55217e1fe68eff7d1b7,amann,1ZWLWVqeEMWMKTlteS0yLH,Love You Goodbye,One Direction,https://i.scdn.co/image/ab67616d0000b273241e4f...,2025-06-19T06:59:30.953684475Z,hi kak lihat kayaknya beneran deket wanita yg ...
...,...,...,...,...,...,...,...,...
33008,684ee57517e1fe68eff710d9,erin,2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-15T15:23:33.485942635Z,kangen erin im erin also miss uu
33009,684ee57417e1fe68eff710d8,fadhly,2AKtROlRcuo37UhkDWiuY5,My Love,Westlife,https://i.scdn.co/image/ab67616d0000b273ee8ea4...,2025-06-15T15:23:32.358975576Z,ih ih yg ngilang deh kmnya aja yg kgn want som...
33010,684ee57317e1fe68eff710d7,jordy,0KqlLyIGuBZWqzNwP9rypc,Last First Kiss,One Direction,https://i.scdn.co/image/ab67616d0000b2734e31e0...,2025-06-15T15:23:31.048231744Z,said didnt want relationship right first kiss ...
33011,684ee56b17e1fe68eff710d4,maritza,15LSJbO8lAck7j25HBA581,i've always loved you,Arash Buana,https://i.scdn.co/image/ab67616d0000b273687cac...,2025-06-15T15:23:23.834725361Z,happy birthday untukk adlina maritza yangg can...
33012,684ee56217e1fe68eff710d2,awik,21acb66djKRlDPJOXRBCkc,Take A Chance With Me,NIKI,https://i.scdn.co/image/ab67616d0000b273d3997a...,2025-06-15T15:23:14.026978056Z,naksir parah kamuu

In [29]:
cleaned_df.to_csv('datasets/cleaned_indo-english-messageDataset.csv', index=False, encoding='utf-8')

# Creating Two Towers Architecture

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from collections import Counter
from sklearn.model_selection import train_test_split
import time

In [31]:
# Setting the GPU or CPU device
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"GPU terdeteksi: {torch.cuda.get_device_name(0)}. Pelatihan akan menggunakan GPU.")
else:
    device = torch.device("cpu")
    print("GPU tidak ditemukan. Pelatihan akan menggunakan CPU.")

GPU terdeteksi: NVIDIA GeForce GTX 1650 Ti. Pelatihan akan menggunakan GPU.

### Message Tower

In [ ]:
dddd